# Generated by Django 4.2.3 on 2023-07-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
