# Generated by Django 4.2.3 on 2023-07-07 19:46

from django.db import migrations, models
import django_backblaze_b2.storage
import hobbynet.topics.models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topic_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='display_name',
            field=models.CharField(default='Topic', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=hobbynet.topics.models.topic_image_generator),
        ),
    ]
