# Generated by Django 4.2.3 on 2023-07-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_display_name_topic_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='display_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
