# Generated by Django 4.2.3 on 2023-07-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_alter_topic_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='privacy',
            new_name='visibility',
        ),
    ]
