# Generated by Django 4.2.3 on 2023-07-08 08:25

from django.db import migrations, models
import django_backblaze_b2.storage
import hobbynet.topics.models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_rename_privacy_topic_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, storage=django_backblaze_b2.storage.BackblazeB2Storage, upload_to=hobbynet.topics.models.topic_image_generator),
        ),
    ]
