# Generated by Django 4.2.3 on 2023-07-10 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_alter_topic_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='display_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('friends', 'Friends'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
