# Generated by Django 4.2.3 on 2023-07-10 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_alter_topic_display_name_alter_topic_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
