# Generated by Django 4.2.3 on 2023-07-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0014_alter_topic_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='visibility',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('friends', 'Friends'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
