# Generated by Django 4.2.3 on 2023-07-08 08:43

from django.db import migrations, models
import hobbynet.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, storage=None, upload_to=hobbynet.profiles.models.profile_image_generator),
        ),
    ]
