# Generated by Django 4.2.3 on 2023-07-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=10, null=True),
        ),
    ]
