# Generated by Django 4.2.3 on 2023-07-07 19:33

from django.db import migrations, models
import django.utils.timezone
import django_backblaze_b2.storage
import hobbynet.posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django_backblaze_b2.storage.BackblazeB2Storage, upload_to=hobbynet.posts.models.posts_image_generator),
        ),
    ]
