# Generated by Django 4.2.3 on 2023-07-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_privacy_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('friends', 'Friends'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
