# Generated by Django 4.2.3 on 2023-07-07 19:33

from django.db import migrations, models
import hobbynet.posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=None, upload_to=hobbynet.posts.models.posts_image_generator),
        ),
    ]
